name: wulkanowy
description: This package provides a SDK for communicating with the Vulcan UONET+ diary through web scraping.
version: 1.0.0

environment:
  sdk: "^3.3.0"

dependencies:
  html: 0.15.4
  dio: ^5.4.3+1
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8

dev_dependencies:
  pedantic: 1.11.1
  test: 1.25.5
